---
:rootdir: /var/lib/repomate/repository
:logdir: /var/log/repomate
:redolog: redo.log
:dpkg: /usr/bin/dpkg
:suites:
    - lenny
    - squeeze
:components:
    - main
    - contrib
:architectures:
    - all
    - amd64
:origin: Repository
:label: Repository
