---
:rootdir: /var/lib/repomate/xing
:logdir: /var/log/repomate
:redolog: redo.log
:dpkg: /usr/bin/dpkg
:suites:
    - lenny
    - squeeze
:components:
    - main
:server:
    :bind: 127.0.0.1
    :port: 1234

