#!/usr/bin/env ruby

require 'rubygems'
require 'slop'
require 'yaml'
require_relative '../lib/configuration'
require_relative '../lib/repomate'

options = Slop.parse do
  banner "RepoMate (A simple debian repository management tool)"
  on :A, :add=, "Add a package to the staging area (full path to file and requires -d)", :argument => true
  on :P, :publish, "Move a package from staging area to production. (No other arguments required)"
  on :L, :load, "Load production links to a specific date/time."
  on :S, :save, "Save production links."
  on :d, :distname=, "Set the name of the distribution.", :argument => true
  on :l, :listpackages, "List packages in a distribution (requires -d)."
  on :h, :help, 'Print this help message', :tail => true do
    puts help
    exit
  end
end

repomate = RepoMate.new

if options.add? && options.distname?
  repomate.stage(options[:add], options[:distname])
elsif options.publish?
  repomate.publish
elsif options.load?
  repomate.load_checkpoint
elsif options.save?
  repomate.save_checkpoint
elsif options.listpackages? && options.distname?
  repomate.list_packages(options[:distname])
elsif options.listpackages?
  repomate.list_packages
else
  puts options.help
end
